#!/usr/bin/env python3
"""EDA of the edge analysis (Model 1) — strong result or bonus?

Uses docs/tables/robust_edges.csv if it exists (generated by scripts/model_edges.py).
Downloads nothing. If it does not exist, it reports and exits.

    python scripts/eda_edges.py

Outputs:
    docs/tables/edge_summary_by_regulator.csv
    docs/tables/top_downstream_genes.csv
    docs/figures/14_edges_per_regulator.png
    docs/figures/15_top_downstream_genes.png
    docs/figures/16_edge_direction_balance.png
    docs/figures/17_edges_by_condition.png
    docs/figures/18_edge_bipartite_network.png
    docs/EDGE_ANALYSIS.md
"""
from pathlib import Path
import sys
import warnings
import numpy as np
import pandas as pd
warnings.filterwarnings("ignore")
import matplotlib
matplotlib.use("Agg")
import matplotlib.pyplot as plt

ROOT = Path(__file__).resolve().parent.parent
TAB = ROOT / "docs" / "tables"
FIG = ROOT / "docs" / "figures"
DOCS = ROOT / "docs"
ACCENT, UP, DOWN, MUT, AMBER, VIOLET = "#0a8f9c", "#d6412f", "#2f5ed0", "#586074", "#b47818", "#6b5fc0"
plt.rcParams.update({"figure.facecolor": "white", "axes.facecolor": "white",
    "axes.edgecolor": "#cfd6e0", "font.size": 10, "axes.spines.top": False,
    "axes.spines.right": False, "axes.grid": True, "grid.color": "#eceff4"})
SEP = "; "


def joinvals(s, n=5):
    return SEP.join(s[:n])


def main():
    edges_path = TAB / "robust_edges.csv"
    if not edges_path.exists():
        print("docs/tables/robust_edges.csv does not exist — run first (optional): "
              "python scripts/model_edges.py")
        sys.exit(0)
    e = pd.read_csv(edges_path)
    e["abs_theta"] = e["theta_post_mean"].abs()
    e["sign"] = np.where(e["theta_post_mean"] > 0, "pos", "neg")
    n_reg = e["perturbed_gene"].nunique()
    n_cond = e["condition"].nunique()
    print(f"== EDA edges · {len(e):,} edges · {n_reg} regulators · {n_cond} conditions ==")

    # ---------- 1. resumen por regulador ----------
    def reg_summary(g):
        gs = g.sort_values("abs_theta", ascending=False)
        return pd.Series({
            "n_edges": len(g),
            "n_positive": int((g["sign"] == "pos").sum()),
            "n_negative": int((g["sign"] == "neg").sum()),
            "mean_abs_theta": round(g["abs_theta"].mean(), 3),
            "median_abs_theta": round(g["abs_theta"].median(), 3),
            "top_downstream_genes": joinvals(list(gs["measured_gene"])),
        })
    by_reg = (e.groupby(["perturbed_gene", "condition"]).apply(reg_summary)
                .reset_index().sort_values("n_edges", ascending=False))
    by_reg.to_csv(TAB / "edge_summary_by_regulator.csv", index=False)
    print("  table → docs/tables/edge_summary_by_regulator.csv")

    # ---------- 2. top downstream genes ----------
    def down_summary(g):
        gs = g.sort_values("abs_theta", ascending=False)
        return pd.Series({
            "n_upstream_regulators": g["perturbed_gene"].nunique(),
            "n_positive_edges": int((g["sign"] == "pos").sum()),
            "n_negative_edges": int((g["sign"] == "neg").sum()),
            "mean_abs_theta": round(g["abs_theta"].mean(), 3),
            "conditions_seen": SEP.join(sorted(g["condition"].unique())),
            "top_upstream_regulators": joinvals(list(gs["perturbed_gene"].drop_duplicates())),
        })
    by_down = (e.groupby("measured_gene").apply(down_summary).reset_index()
                 .sort_values(["n_upstream_regulators", "mean_abs_theta"], ascending=False))
    by_down.to_csv(TAB / "top_downstream_genes.csv", index=False)
    print("  table → docs/tables/top_downstream_genes.csv")

    # ---------- figures ----------
    # 14 — edges per regulator (stacked pos/neg)
    r = by_reg.groupby("perturbed_gene")[["n_positive", "n_negative"]].sum().sort_values("n_positive")
    fig, ax = plt.subplots(figsize=(6.8, 4))
    ax.barh(r.index, r["n_positive"], color=UP, label="activation (θ>0)")
    ax.barh(r.index, r["n_negative"], left=r["n_positive"], color=DOWN, label="repression (θ<0)")
    ax.set_xlabel("number of robust edges"); ax.set_title("Edges per regulator", fontweight="bold")
    ax.legend(frameon=False, loc="lower right"); ax.grid(axis="y")
    fig.tight_layout(); fig.savefig(FIG / "14_edges_per_regulator.png", dpi=135, bbox_inches="tight"); plt.close(fig)

    # 15 — top downstream by number of upstream regulators
    td = by_down.head(15).iloc[::-1]
    fig, ax = plt.subplots(figsize=(6.8, 5))
    ax.barh(td["measured_gene"], td["n_upstream_regulators"], color=ACCENT, edgecolor="white")
    ax.set_xlabel(f"number of upstream regulators (of {n_reg})")
    ax.set_title("Most convergent downstream (shared targets)", fontweight="bold", fontsize=11)
    ax.grid(axis="y"); ax.set_xticks(range(0, n_reg + 1))
    fig.tight_layout(); fig.savefig(FIG / "15_top_downstream_genes.png", dpi=135, bbox_inches="tight"); plt.close(fig)

    # 16 — direction balance (100% stacked per regulator)
    fig, ax = plt.subplots(figsize=(6.8, 4))
    frac_pos = r["n_positive"] / (r["n_positive"] + r["n_negative"])
    ax.barh(r.index, frac_pos, color=UP, label="activation")
    ax.barh(r.index, 1 - frac_pos, left=frac_pos, color=DOWN, label="repression")
    ax.axvline(0.5, color=MUT, ls="--", lw=1)
    ax.set_xlim(0, 1); ax.set_xlabel("fraction of edges"); ax.grid(axis="y")
    ax.set_title("Direction balance — these regulators are mostly activators",
                 fontweight="bold", fontsize=10.5)
    ax.legend(frameon=False, loc="lower center", ncol=2)
    fig.tight_layout(); fig.savefig(FIG / "16_edge_direction_balance.png", dpi=135, bbox_inches="tight"); plt.close(fig)

    # 17 — edges per condition
    cc = e.groupby(["condition", "sign"]).size().unstack(fill_value=0)
    for c in ("pos", "neg"):
        if c not in cc: cc[c] = 0
    fig, ax = plt.subplots(figsize=(5.6, 3.8))
    ax.bar(cc.index, cc["pos"], color=UP, label="activation")
    ax.bar(cc.index, cc["neg"], bottom=cc["pos"], color=DOWN, label="repression")
    ax.set_ylabel("number of edges"); ax.set_title("Edges per condition", fontweight="bold")
    ax.legend(frameon=False); ax.grid(axis="x")
    fig.text(0.5, -0.02, "Note: the demo picked the peak condition per regulator → Rest is missing",
             ha="center", fontsize=8, color=MUT, style="italic")
    fig.tight_layout(); fig.savefig(FIG / "17_edges_by_condition.png", dpi=135, bbox_inches="tight"); plt.close(fig)

    # 18 — red bipartita regulador → downstream convergentes
    core = by_down[by_down["n_upstream_regulators"] >= max(2, n_reg - 2)].head(18)["measured_gene"].tolist()
    sub = e[e["measured_gene"].isin(core)]
    regs = list(r.index)                                   # orden por nº de edges
    fig, ax = plt.subplots(figsize=(7.4, 8))
    ry = {g: i for i, g in enumerate(np.linspace(1, len(core), len(regs)))}
    reg_y = {g: v for g, v in zip(regs, np.linspace(1, len(core), len(regs)))}
    down_y = {g: i + 1 for i, g in enumerate(core[::-1])}
    for _, row in sub.iterrows():
        col = UP if row["theta_post_mean"] > 0 else DOWN
        ax.plot([0, 1], [reg_y[row["perturbed_gene"]], down_y[row["measured_gene"]]],
                color=col, lw=0.7, alpha=min(0.9, 0.25 + row["abs_theta"] / 4))
    for g, y in reg_y.items():
        ax.scatter(0, y, s=90, color=VIOLET, zorder=3)
        ax.text(-0.03, y, g, ha="right", va="center", fontsize=9, fontweight="bold")
    for g, y in down_y.items():
        ax.scatter(1, y, s=40, color="#888", zorder=3)
        ax.text(1.03, y, g, ha="left", va="center", fontsize=8)
    ax.set_xlim(-0.35, 1.4); ax.set_ylim(0, len(core) + 1); ax.axis("off")
    ax.text(0, len(core) + 0.8, "regulators", ha="center", fontsize=9, color=VIOLET, fontweight="bold")
    ax.text(1, len(core) + 0.8, "convergent downstream", ha="center", fontsize=9, color="#555", fontweight="bold")
    ax.set_title("Bipartite network — targets shared by the SAGA complex",
                 fontweight="bold", fontsize=11)
    ax.text(0.5, -0.4, "red = activation · blue = repression", ha="center", fontsize=8, color=MUT)
    fig.tight_layout(); fig.savefig(FIG / "18_edge_bipartite_network.png", dpi=135, bbox_inches="tight"); plt.close(fig)
    print("  figures → docs/figures/14–18_*.png")

    # ---------- EDGE_ANALYSIS.md ----------
    shared2 = int((e.groupby("measured_gene")["perturbed_gene"].nunique() >= 2).sum())
    pos_frac = (e["sign"] == "pos").mean()
    md = f"""# Edge analysis (Model 1) — strong result or bonus?

## What was analyzed

The uncertainty-aware effect network `docs/tables/robust_edges.csv`: **{len(e):,}** robust edges
(`P(|effect|>1.5×)>0.8`) from **{n_reg} regulators** × **{n_cond} conditions**, read by slice from the
remote `DE_stats.h5ad`. Summarized per regulator and per downstream gene, with direction and convergence.

## Do they look useful?

**Yes as a proof-of-concept, not as a strong result.** Signals in favor:

- **Coherent convergence**: {shared2} downstream genes are targeted by ≥2 regulators. All {n_reg}
  regulators are co-members of the **SAGA complex** (TADA1/TADA2B/SGF29/SUPT20H) → sharing
  targets is exactly what's expected, and **validates that the method recovers real biological structure**.
- **Interpretable direction**: {pos_frac*100:.0f}% of the edges are activating, consistent with
  SAGA as a transcriptional coactivator.
- Effect magnitudes are modest and well bounded (median |θ| ≈ {e['abs_theta'].median():.2f}).

## Why it is NOT a strong result (yet)

- **Minimal coverage**: {n_reg} of 7,913 regulators (0.08%), **selected by the EB ranking**
  → a sample biased toward a single complex, not representative of the regulatory landscape.
- **Incomplete conditions**: only {', '.join(sorted(e['condition'].unique()))} (the demo took the
  peak condition per regulator; **Rest is missing**).
- **Remote latency**: scaling to ~150 regulators is ~11 min of h5ad reads (4.5 s/row measured).
- **Probability semantics**: `p_abs_effect_gt_1p5x` is **P(effect magnitude > 1.5×)**,
  NOT P(a causal edge exists). There is no network-level FDR control or sparsity (spike-and-slab).

## Verdict

Keep it as a **bonus / proof-of-concept**: it shows the pipeline produces a biologically sensible
uncertainty-aware effect network without downloading 1.8 TB, but the coverage and semantics do not
yet support network-scale claims. To promote it to a strong result: run the ~150 top regulators over
all 3 conditions and add P(edge) with a sparse prior.
"""
    (DOCS / "EDGE_ANALYSIS.md").write_text(md)
    print("  doc → docs/EDGE_ANALYSIS.md")
    print(f"\n  VERDICT: bonus / proof-of-concept "
          f"({n_reg} regulators, {n_cond} cond, {shared2} shared targets)")
    print("✓ Edge EDA complete.")


if __name__ == "__main__":
    main()
